# See variable settings in .env
version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pgadmin4:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_LISTEN_PORT=${INTERNAL_PORT}
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}